global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'xiaozhou-order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['xiaozhou-order:8089']

  - job_name: 'xiaozhou-product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['xiaozhou-product:8090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
